/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:21:25 GMT 2025
 */

package com.rems.boot.model.vo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rems.boot.model.vo.ResultVo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ResultVo_ESTest extends ResultVo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResultVo resultVo0 = new ResultVo();
  }
}
