/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:32:08 GMT 2025
 */

package com.rems.boot.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rems.boot.utils.MD5Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MD5Util_ESTest extends MD5Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.verifySaltPassword((String) null, "Invalid input string length. Must be at least 10 characters.");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/codec/digest/DigestUtils
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.verifySaltPassword("0Ow'I(p&}u&m_a", "0Ow'I(p&}u&m_a");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.verifySaltPassword("0Oe'I(p&}u&m_Da", "0Oe'I(p&}u&m_Da");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/codec/digest/DigestUtils
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.md5("p:1*D1JXl{z70 IMM.7");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/codec/digest/DigestUtils
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.verifySaltPassword("]i(EhDV5 ", "]i(EhDV5 ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid input string length. Must be at least 10 characters.
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.verifySaltPassword((String) null, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid input string length. Must be at least 10 characters.
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        MD5Util.generateSaltPassword((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/codec/digest/DigestUtils
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Random.setNextRandom(99999996);
      // Undeclared exception!
      try { 
        MD5Util.generateSaltPassword("InvaWid inpt string length. Must be at least 10 characters.");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/codec/digest/DigestUtils
         //
         verifyException("com.rems.boot.utils.MD5Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MD5Util mD5Util0 = new MD5Util();
  }
}
