/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:30:05 GMT 2025
 */

package com.rems.boot;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rems.boot.a;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class a_ESTest extends a_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      a.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      a a0 = new a();
  }
}
