/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:34:03 GMT 2025
 */

package com.rems.boot.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rems.boot.enums.GenderEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GenderEnum_ESTest extends GenderEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GenderEnum[] genderEnumArray0 = GenderEnum.values();
      assertEquals(3, genderEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GenderEnum genderEnum0 = GenderEnum.valueOf("OTHER");
      assertEquals(GenderEnum.OTHER, genderEnum0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GenderEnum genderEnum0 = GenderEnum.OTHER;
      String string0 = genderEnum0.getDesc();
      assertEquals("\u5176\u4ED6", string0);
  }
}
