/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:27:26 GMT 2025
 */

package com.rems.boot.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rems.boot.enums.LayCodeEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LayCodeEnum_ESTest extends LayCodeEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LayCodeEnum[] layCodeEnumArray0 = LayCodeEnum.values();
      assertEquals(2, layCodeEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LayCodeEnum layCodeEnum0 = LayCodeEnum.valueOf("SUCCESS");
      assertEquals(0, layCodeEnum0.getCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LayCodeEnum layCodeEnum0 = LayCodeEnum.valueOf("ERROR");
      assertEquals("error", layCodeEnum0.getDesc());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LayCodeEnum layCodeEnum0 = LayCodeEnum.SUCCESS;
      int int0 = layCodeEnum0.getCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LayCodeEnum layCodeEnum0 = LayCodeEnum.ERROR;
      int int0 = layCodeEnum0.getCode();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LayCodeEnum layCodeEnum0 = LayCodeEnum.ERROR;
      String string0 = layCodeEnum0.getDesc();
      assertEquals("error", string0);
  }
}
