/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:40:34 GMT 2025
 */

package com.rems.boot.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rems.boot.enums.UserTypeEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserTypeEnum_ESTest extends UserTypeEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = UserTypeEnum.getName("student");
      assertEquals("\u5B66\u751F", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserTypeEnum[] userTypeEnumArray0 = UserTypeEnum.values();
      assertEquals(4, userTypeEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserTypeEnum userTypeEnum0 = UserTypeEnum.valueOf("ADMIN");
      assertEquals("admin", userTypeEnum0.getCode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserTypeEnum userTypeEnum0 = UserTypeEnum.STUDENT;
      String string0 = userTypeEnum0.getName();
      assertEquals("\u5B66\u751F", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserTypeEnum userTypeEnum0 = UserTypeEnum.STUDENT;
      String string0 = userTypeEnum0.getCode();
      assertEquals("student", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        UserTypeEnum.getName("\u666E\u901A\u7528\u6237");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // \u4E0D\u5B58\u5728\u7684\u7528\u6237\u7C7B\u578B
         //
         verifyException("com.rems.boot.enums.UserTypeEnum", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = UserTypeEnum.getName("user");
      assertEquals("\u666E\u901A\u7528\u6237", string0);
  }
}
