/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 15:41:53 GMT 2025
 */

package com.rems.boot.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.rems.boot.enums.UserStatusEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserStatusEnum_ESTest extends UserStatusEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserStatusEnum[] userStatusEnumArray0 = UserStatusEnum.values();
      assertEquals(3, userStatusEnumArray0.length);
  }
}
